dict/dict/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("dictApp.urls"))
]

dict/dictApp/urls.py
from django.urls import path
from dictApp import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "dictApp"

urlpatterns = [
    path('', views.home, name="home"),
    path('home/', views.home),
    path('words_list/', views.wordsList, name = 'wordslist'),
    path('add_words/', views.addWords, name = 'addwords')
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dict/dictApp/models.py
from django.db import models
from django.core.validators import RegexValidator

class Word(models.Model):
    only_letters = RegexValidator(r'^[a-zA-Zа-яА-ЯЁё]*$', 'Для ввода разрешены только буквы.')
    word = models.CharField(max_length=50, blank=False, validators=[only_letters], unique=True)
    translation = models.CharField(max_length=50, blank=False, validators=[only_letters], unique=True)

    def __str__(self):
        return self.word

dict/dictApp/forms.py
from django.forms.models import ModelForm
from dictApp.models import Word

class WordForm(ModelForm):
    class Meta:
        model = Word
        fields = '__all__'

dict/dictApp/views.py
from django.shortcuts import render
from dictApp.models import Word
from dictApp.forms import WordForm

def home(request):
    context = {
        'PageTitle':"My dictionary",
        'active':'Home'
    }
    return render(request, 'home.html', context)

def wordsList(request):
    context = {
        'PageTitle':"Words list",
        'active':'WordsList',
        'words':Word.objects.all()
    }
    return render(request, 'wordslist.html', context)

def addWords(request):
        context = {
            'PageTitle':"Add words",
            'active':'AddWords',
            'form':WordForm
        }
        if request.method == "GET":
            return render(request, 'addwords.html', context)
        else:
            try:
                word = Word.objects.create(word=request.POST.get('word'), translation=request.POST.get('translation'))
                word.save()
                context["success"] = "Слово успешно добавлено"
            except Exception as ex:
                context["error"] = ex
            return render(request, 'addwords.html', context)

dict/templates/addwords.html
{% extends 'index.html'%}

{% block content %}
            <div class="container">
                <h1 class="text-center" style="margin-bottom: 20px"> Добавить слово </h1>
                <form method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Добавить слово" class="btn btn-primary btn-lg">
                </form>
            </div>
        {% if error %}
            <script> alert('{{error}}') </script>
        {% endif %}
        {% if success %}
            <script> alert('{{success}}') </script>
        {% endif %}
{% endblock %}

dict/templates/home.html
{% extends 'index.html'%}

{% block content %}
    <h1 class="text_center"> Что-то с чем-то, вообщем не важно </h1>
    <h2> Если хотите можете сделать тут словарик, а можете не делать. Решайте сами </h2>>
    <img src="media/meg.png" style="max-width: 1000px">
{% endblock %}

dict/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{PageTitle}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'dictApp:home' %}">Словарь</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if active == 'Home' %} active {% endif %}" aria-current="page"
             href="{% url 'dictApp:home' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if active == 'WordsList' %} active {% endif %}" aria-current="page"
             href="{% url 'dictApp:wordslist' %}">Список слов</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if active == 'AddWords' %} active {% endif %}" aria-current="page"
             href="{% url 'dictApp:addwords' %}">Добавление слов</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

dict/templates/wordslist.html
{% extends 'index.html'%}

{% block content %}
    <div class="container">
        <h1 class="text-center"> Словарь </h1>
        <table class="table table-bordered">
            <tr class="row text-center">
                <th class="col-6"> Слово </th>
                <th class="col-6"> Перевод </th>
            </tr>
            {% for word in words %}
            <tr class="row text-center">
                <td class="col-6"> {{word.word}} </td>
                <td class="col-6"> {{word.translation}} </td>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}